### ISSUE TITLE
this mess up my ubuntu box!

### ISSUE THREAD

**Issue by jaylex32** [coder8338/appbox_swizzin_installer#1]
the script mess up my ubuntu and now I can even ssh to it!

**Comment by coder8338** [comment]
Which version of ubuntu did you install it on? Did you have anything else installed on it? Was the old script used before?

Can you paste the installer log here

**Comment by jaylex32** [comment]
> Which version of ubuntu did you install it on? Did you have anything else installed on it? Was the old script used before?
> 
> Can you paste the installer log here

I was able to repair my apps from the other script but now I can't ssh to it, if I reset the ubuntu app it will work temporary but then it just doesn't connect with a error "Connection reset by peer" any ideas? 
thanks!

**Comment by coder8338** [comment]
I can't seem to reproduce this. Can you let me know what apps you installed?

**Comment by jaylex32** [comment]
> I can't seem to reproduce this. Can you let me know what apps you installed?

I open a ticket with Appbox and this is the replied:

For some reason your Ubuntu was missing the /run/sshd directory, adding back seems to have fixed it.

is working now but the script messed up with the sshd directory.

thanks

**Comment by jaylex32** [comment]
The apps that I installed other than radarr and sonarr are nzbget and Ombi.
